### ISSUE TITLE
Add Dashboard option to show only changed messages over a time window

### ISSUE THREAD

**Issue by peplin** [openxc/openxc-python#43]
To facilitate reverse engineering stuff on CAN, it'd be useful to automatically filter out CAN messages or signals that aren't changing. For example if a message hasn't changed in 2 seconds, remove it from the list. At some point you'll be left with a much smaller set of messages and it should be more obvious which changes when you hit a button, for example.

**Comment by jstoke53** [comment]
pull request: [#134](https://github.com/openxc/openxc-python/pull/134)
