### ISSUE TITLE
obd2scanner can get confused by translated output format

### ISSUE THREAD

**Issue by peplin** [openxc/openxc-python#50]
[Original report](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openxc/3daEFKpjKH4/2sNRrJ2L_vwJ)

It looks like the `openxc-obd2scanner` tool may get confused if the VI is also outputting data in the [translated message format](https://github.com/openxc/openxc-message-format#single-valued). We should able to reproduce this by running the scanner against the pre-built automatic OBD-II query build.

**Comment by jwschmo** [comment]
in diagnostics.py as a stop gap can add the following functions:

def find_in_tuples(tuples, term1, term2):
    matching_set = []
    for tuple in tuples:
        if term1 in tuple:
            matching_set.append(tuple)
        if term2 in tuple:
            matching_set.append(tuple)
    return matching_set


AND - modify this line in diagnostic_request funciton:

print("Response: %s" % find_in_tuples(response, 'status', 'mode'))

**Comment by jstoke53** [comment]
issue fixed in pull request [#137](https://github.com/openxc/openxc-python/pull/137)
