### ISSUE TITLE
Signals.cpp generation references functions not supported for VI firmware v7

### ISSUE THREAD

**Issue by jon-mullen** [openxc/openxc-python#70]
I am using the Python scripts to generate signals.cpp.

Several message handlers throw errors when trying to compile the VI firmware.  Specifically, I've seen errors from handleDoorStatusMessage when trying to compile the public message set and handleTurnSignalMessage when doing a proprietary set.

**Comment by zacnelson** [comment]
@jon-mullen I think the issues you found should be resolved in vi-firmware. Most likely the json and cpp files you are using to compile the firmware need to be updated to the latest API. 

Let's track this in vi-firmware.

**Comment by zacnelson** [comment]
@jon-mullen if it's an openxc-python issue we can reopen.
