### ISSUE TITLE
Re-evaluate Python 3 support as protobuf actively works to support it

### ISSUE THREAD

**Issue by mitchellrj** [openxc/openxc-python#71]
[The docs](http://python.openxcplatform.com/en/master/) state that Python 3 support had to be dropped because [protobuf](https://github.com/google/protobuf/) did not support it. Protobuf 2.6.0 added Python 3 support. Can you please reevaluate Python 3 support for the OpenXC Python library?

**Comment by peplin** [comment]
Oh, cool! It's definitely worth another try. Are you interested in giving it a shot and sending a pull request?

**Comment by mitchellrj** [comment]
It turns out that while the docs for protobuf do claim to support Python 3, the truth is that it doesn't. There are several open pull requests for this problem that Google seem to be failing to deal with.

Perhaps you could keep this ticket open though as a reminder to check back at some later date?

**Comment by peplin** [comment]
Sounds good - I re-titled this ticket so I don't forget what we're waiting on. If you have the links to the PRs handy, that would be good to post in here too.

**Comment by emarsman** [comment]
When we get to this, try this tool? 

http://python-future.org/futurize.html

**Comment by danyeaw** [comment]
Is there any update on plans for modern Python support? The [clock is ticking](https://pythonclock.org/).

**Comment by pjt0620** [comment]
OpenXC has been updated to support python 3 #114
