### ISSUE TITLE
openxc-dashboard should handle evented messages better

### ISSUE THREAD

**Issue by zacnelson** [openxc/openxc-python#73]
Noticed this today while testing. I have a fix in place and will submit a pull request shortly. 

Right now, the dashboard shows door_status signals coming through properly, but doesn't provide the correct true/false state for each door. Instead it looked like:

`Driver: ?`  instead of `Driver: True`

**Comment by emarsman** [comment]
Along with openxc/openxc-android#248, should update the display to be able to see all 4 statuses. I think this will require 4 lines instead of fitting it all on one.

**Comment by jstoke53** [comment]
I confirmed that the current openxc-dashboard does provide the correct values for all door_status events.
