### ISSUE TITLE
Need support for new JSON commands for C5 devices

### ISSUE THREAD

**Issue by emarsman** [openxc/openxc-python#75]
cell config, rtc, sd card status

**Comment by emarsman** [comment]
@peplin For updating openxc-python with new openxc-message-format (openxc/openxc_pb2.py), is the process just to copy it from openxc-message-format? Any particular reason openxc-message-format isn't included as a submodule? Didn't see this documented anywhere so just want to make sure I'm understanding it correctly.

**Comment by peplin** [comment]
Yup, it's just a copy - I think it was just for simplicity, since it's all contained within a single file.

**Comment by emarsman** [comment]
v0.13.0 fixes this.
