### ISSUE TITLE
Discontinue support testing for python 2.6?

### ISSUE THREAD

**Issue by emarsman** [openxc/openxc-python#79]
Is there any reason to continue supporting/testing python 2.6? Requires installing both 2.6 and 2.7 which seems pointless at this time.

**Comment by peplin** [comment]
If you don't want to install 2.6 locally, I think you can tell tox to only run a single environment: 

```
tox -e py27
```

There's not too many distros stuck at Python 2.6 these days, but since it's basically free to have it verify against 2.6 in CI, I think we should keep it around.

**Comment by emarsman** [comment]
I just edit tox.ini to only run 27 so that it works from fab or command line. 

Testing is only useful if you're going to fix any issues it uncovers. At this point, I don't think we should spend any effort fixing issues that only apply to 2.6. If somebody is still using it for something, then that's different. 

Time would be better spent looking at 3.0. I understand that is a bigger undertaking.

**Comment by emarsman** [comment]
Argh. Looks like pyserial no longer is compatible with python 2.6. This travis build (https://travis-ci.org/openxc/openxc-python/jobs/156588415#L149) pointed to the new pyserial 3.1.1 as causing an error. The previous build used pyserial 3.0.1 (https://travis-ci.org/openxc/openxc-python/jobs/129154982#L182).

According to current pyserial docs, it requires Python 2.7 or later. http://pyserial.readthedocs.io/en/latest/pyserial.html#requirements

Choices I see are sticking with pyserial 3.0.1 (or 2.7) or removing python 2.6. Thoughts @peplin @zacnelson ?

**Comment by zacnelson** [comment]
I'm OK with leaving 2.6 out and updating pyserial accordingly. That being said, I don't use python 2.6 and I'm not aware of those here that might. @peplin what do you think?

**Comment by peplin** [comment]
I think we can drop 2.6, I have no objections. We should pin the pyserial version to 3.1.1 to avoid any surprises in the future, though.
