### ISSUE TITLE
Diagnostic Request

### ISSUE THREAD

**Issue by jwschmo** [openxc/openxc-python#82]
OpenXC Python command:
openxc-diag add --message 0x7df --mode 0x3

Results in a dump of the entire buffer of CAN Frames.

**Comment by emarsman** [comment]
This should fix that issue. https://github.com/openxc/openxc-python/tree/diagnosticResponseCleanup

**Comment by jwschmo** [comment]
There isn't anything at that link.

**Comment by emarsman** [comment]
Sorry, that branch got merged and deleted. Here is the PR #86 . It is currently in 'next' if you want to try it out.

**Comment by peplin** [comment]
Since #86 is merged, I'll close this unless it's confirmed to not fix the bug. Thanks!
