### ISSUE TITLE
USB commands require --format json when it should default

### ISSUE THREAD

**Issue by emarsman** [openxc/openxc-python#90]
In some cases, USB commands require --format json, but that should be the default. Something in the auto-detect logic isn't working correctly.

File "/Users/Belina/openxc-python/openxc/sources/base.py", line 63, in streamer

    raise MissingPayloadFormatError("Unable to auto-detect payload "

openxc.sources.base.MissingPayloadFormatError: Unable to auto-detect payload format, must specify manually with --format [json|protobuf]

**Comment by PPRAKA30** [comment]
Reference: #138
